### PR TITLE
Update onboarding doc to v1.2

### PR DESCRIPTION
**Pull request by JieXiong9119**
Add publication workflow diagram

### CODE REVIEW

**Comment by JieXiong9119** [comment]
Do I need to change anywhere else like link to updated document?

**Review by kflemin — APPROVED** [review]
👍

**Comment by nllong** [comment]
Looks good, should these test be passing? I just updated from develop, so hopefully they pass this time.

**Review by nllong — APPROVED** [review]

**Comment by nllong** [comment]
> Do I need to change anywhere else like link to updated document?

I don't think so, you just replaced the file which should work just fine.

**Comment by nllong** [comment]
I'm going to merge this knowing that the issue is on gbxml side. Issue to track is [here](https://github.com/BuildingSync/schema/issues/393)

**Pull request merged**
